services:
  backend:
    build: ./backend
    container_name: battleship-backend
    expose:
      - "18080"
    restart: unless-stopped
    networks:
      - battleship-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: battleship-nginx
    ports:
      - "0.0.0.0:80:80" # Доступен из локальной сети
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - battleship-network

networks:
  battleship-network:
    driver: bridge
